### ISSUE TITLE
Not all cinematics are dubbed

### ISSUE THREAD

**Issue by JulioJMZ** [wagrenier/Zero2Undub#1]
I´m not sure if I made a mistake using the program but the first cinematic has japanese dub, then while playing japanese is spoken too, but the second cinematic has english dub. I haven´t play the game yet, just testing it so I don´t know if it keeps happening.

**Comment by wagrenier** [comment]
Normal, I cannot insert files that are bigger in the japanese version than the Us version. They have to be either compressed or changed video file. Once I am done with the Fatal Frame 1 undub I will come back to this.

**Comment by wagrenier** [comment]
Next versio  should have that fixed. I will now close this issue.
