### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by MaskedMM** [wagrenier/Zero2Undub#10]
I already played the game with the patch once and it worked perfectly, I was about to replay it again in Japanese "Hard" but for some reason it's not working anymore, when I start the game *Both in normal or hard" the cutscene have the audio in Japanese but the game still have the audio in English *And yes the subtitles are on* Can you help me? I don't know if it is a configuration on my emulator or maybe a bug in the patch, since I use a pre-patched version *Cdromance*

**Comment by wagrenier** [comment]
Try to redownload the game or repatch it without the safe mode enabled. This mode makes it so that some audio will be in english

**Comment by wagrenier** [comment]
Will close this due to never receiving any updates. Reopen it if you have further updates.
