### ISSUE TITLE
No titlescreen music, freezes shortly after intro FMV

### ISSUE THREAD

**Issue by clockworkprince** [wagrenier/Zero2Undub#9]
When I run the game patched (v1.0.1, no safe mode) using PCSX2, I get no title music and the game freezes as soon as Mio's first voice clip where she calls out for Mayu is supposed to play. The unpatched ISO runs completely fine, so I suspect there's something about the patch that's not working right. (If there's any settings I should use in PCSX2, do let me know.)

**Comment by wagrenier** [comment]
Can you post the log output of PCSX2? Right now I can't help you since you are the only one with the issue and it does not happen on real hardware.

**Comment by clockworkprince** [comment]
Here's the log. I started a new game and played until the freeze happens. No input is registered anymore at this point and the screen is frozen. 
[PCSX2 log FF2Undub.txt](https://github.com/wagrenier/Zero2Undub/files/10452050/PCSX2.log.FF2Undub.txt)

**Comment by wagrenier** [comment]
You are trying to run a us game with a jp bios. Also the log shows sign of being a problem of your emulator. Can you add more logs sources, like elf out and cd/dvd r/w.

**Comment by clockworkprince** [comment]
> You are trying to run a us game with a jp bios. Also the log shows sign of being a problem of your emulator. Can you add more logs sources, like elf out and cd/dvd r/w.

This BIOS does not give issues with my other US games, but to try and see whether it makes a difference I switched over to one that's for the US. It still gives the same issues, unfortunately. 

For the log I turned on Dev/Verbose, CDVD Reads and ELF. If I need to enable everything instead, do let me know! 

[PCSX2 log FF2Undub - US BIOS.txt](https://github.com/wagrenier/Zero2Undub/files/10461286/PCSX2.log.FF2Undub.-.US.BIOS.txt)

**Comment by wagrenier** [comment]
Can you enable all options and do a console clear before? I see a lot of repeating reboot sequences. Also the game seems to still be loading content from the disc when the app was shutdown.

**Comment by wagrenier** [comment]
Thinking about it, it could be that your original iso is a byte bigger or shorter than the one I used and leads to that crash?

**Comment by wagrenier** [comment]
If you want, you can join the discord server for the mikompilation project (creating a pc port of FF2), where I have a section dedicated to support for my undubs.

https://discord.gg/Ap4Sfcmwd9

**Comment by wagrenier** [comment]
Closing as fixed, issue was a bad dump of either the US or JP versions that lead to a wrong offset
